<?php

/**
 * Copyright (C) 2014 Orange
 */

namespace Kronos\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends EntityRepository {

    public function findDatasByLineAndWeek($lineId, $monday, $sunday) {
        $qb = $this->createQueryBuilder('d')
                ->select('d')
                ->where('d.line = :line')
                ->andWhere('d.date >= :monday')
                ->andWhere('d.date <= :sunday')
                ->orderBy('d.date', 'ASC')
                ->setParameter('line', $lineId)
                ->setParameter('monday', $monday->format('Y-m-d H:i:s'))
                ->setParameter('sunday', $sunday->format('Y-m-d H:i:s'));
        $result = $qb->getQuery()->getResult();

        return $result;
    }

}
